apiVersion: v1
kind: Secret
metadata:
  name: gitlab-backup-storage
  namespace: gitlab
type: Opaque
stringData:
  config: |
    [default]
    access_key = minio
    secret_key = minio-password
    bucket_location = us-east-1
    host_base = minio.gitlab.svc.cluster.local:9000
    host_bucket = minio.gitlab.svc.cluster.local:9000
    use_https = False
    signature_v2 = False
