global:
  hosts:
    domain: gitlab.local
    externalIP: 127.0.0.1
  edition: ce
  ingress:
    configureCertmanager: false
    enabled: true
  psql:
    host: postgresql.gitlab.svc.cluster.local
    port: 5432
    username: gitlab
    database: gitlabhq_production
    password:
      secret: gitlab-postgresql-password
      key: postgresql-password
  redis:
    host: redis-master.gitlab.svc.cluster.local
    port: 6379
    auth:
      enabled: true
      secret: gitlab-redis-password
      key: redis-password
  appConfig:
    object_store:
      enabled: true
      connection:
        secret: gitlab-minio-secret
        key: connection
    lfs:
      bucket: gitlab-lfs
    artifacts:
      bucket: gitlab-artifacts
    uploads:
      bucket: gitlab-uploads
    packages:
      bucket: gitlab-packages
    backups:
      bucket: gitlab-backups
      tmpBucket: gitlab-tmp
      connection:
        secret: gitlab-backup-storage
        key: config
  registry:
    bucket: gitlab-registry
  extraEnv:
    BYPASS_SCHEMA_VERSION: true

certmanager:
  enabled: false

certmanager-issuer:
  email: admin@gitlab.local

nginx-ingress:
  enabled: true

prometheus:
  install: false

gitlab-runner:
  install: false

postgresql:
  install: false

redis:
  install: false

registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
  storage:
    secret: gitlab-registry-storage
    key: config

gitlab:
  toolbox:
    backups:
      objectStorage:
        config:
          secret: gitlab-backup-storage
          key: config
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  gitlab-exporter:
    enabled: false
