Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.box = "bento/debian-13"

  config.vm.define "snourryS" do |server|
    server.vm.hostname = "snourryS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |v|
      v.name = "snourryS"
      v.memory = 2048
      v.cpus = 2
      v.linked_clone = true
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
