Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "snourryS" do |server|
    server.vm.hostname = "snourryS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |v|
      v.name = "snourryS"
      v.memory = 8192
      v.cpus = 4
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
