Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "snourryS" do |server|
    server.vm.hostname = "snourryS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |v|
      v.name = "snourryS"
      v.memory = 1024
      v.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "snourrySW" do |worker|
    worker.vm.hostname = "snourrySW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |v|
      v.name = "snourrySW"
      v.memory = 1024
      v.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
